grammar DrawGrammar;

INT: [0-9]+;
BOOL: 'true' | 'false';
EXPRESSAO: INT;
PONTO2D: EXPRESSAO','EXPRESSAO;
DIMENSAO: EXPRESSAO'~'EXPRESSAO;
INTERVALO: ('[' | ']')EXPRESSAO', 'EXPRESSAO('[' | ']');
COR: (EXPRESSAO)?'|'EXPRESSAO'|'(EXPRESSAO)?;